on: 
    milestone:
      types: [closed]
  name: Milestone Closure
  jobs:
    create-release-notes:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Create Release Notes
        uses: decathlon/release-notes-generator-action@feat_release_notes_configuration
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FOLDER: temp_release_notes
          USE_MILESTONE_TITLE: "true"